.github/workflows/CI.yml
- enables semantic release on pushes to `main`
- so we can use it
=> Enable semantic release on main

src/example.test.ts, src/example.ts, src/index.ts, src/loadScript.test.ts, src/loadScript.ts, src/types.ts
- add `loadScript`, ported/refactored from [frontend](https://github.com/guardian/frontend/blob/main/static/src/javascripts/lib/load-script.js)
- removes stub files
- want to use it outside frontend
- will remove in frontend once this is published
=> Add loadScript

.github/workflows/CI.yml, .releaserc.json, CHANGELOG.md, package.json, yarn.lock
- stops committing bumps to `package.json` and `CHANGELOG.md` when releasing
- we need an access token with admin rights to do it, which the default GitHub user in actions does not have
- they aren't needed – releases will still be tagged in git, and available from NPM and GitHub with the correct version in `package.json`, it just won't be committed to `main`
- messages like https://github.com/guardian/commercial-core/pull/58#issuecomment-708456726 won't come from me!
_nb fix: prefix is just to force a patch release on merge to test it_
=> fix: do not commit bumps to package.json in CD

src/storage.test.ts, src/storage.ts
- adds `getRaw` and `setRaw` methods
- they're used a lot, and wrapping them in the checks is useful
=> feat: add getRaw and setRaw to storage

src/storage.test.ts, src/storage.ts
- explicitly returns an `any` from `Storage#get` because that's what `JSON.parse` does
- an `unknown` is inaccurate, and makes this method harder to use than using `JSON.parse` itself, which it shouldn't
=> fix: update Storage#get return type

.eslintrc.json, README.md, package.json, rollup.config.js, tsconfig.json, yarn.lock
- adds an `unpkg` export that links to an ES2015, minified build
- enables bundlesize checking via `badgesize.io`
- also adds ability to use `<script src="https://unpkg.com/@guardian/libs/dist/umd/index.min.js"></script>`
=> chore: add unpkg export

src/getLocale.test.ts, src/getLocale.ts
only performs locale lookup once, uses the found value after that
does less work, and looking in `localStorage` is a blocking action
=> perf: cache the value of locale on first successful lookup

package.json, src/getLocale.ts
- removes the need to disable eslint by asserting the type at right point
- adds `types` field to package 
typescript thought `getLocale` returned possible `any` value
=> fix: getLocale types

README.md, src/index.ts, src/isUndefined.README.md, src/isUndefined.test.ts, src/isUndefined.ts
adds `isUndefined`
standardise use
ref
- https://chat.google.com/room/AAAAWwBdSMs/RjEae7ZfPAQ
- https://github.com/guardian/consent-management-platform/pull/371#discussion_r534217070
=> feat: add isUndefined

src/logger.teams.ts
Adds TX Team.
So we can start logging with style 😎 
I found it hard to look at a list of hex codes and pick a colour which wasn't already taken, so I've added brief descriptions as comments next to each entry. Please shout if that's not wanted and I'll remove (I've kept the commit separate).
=> fix: Add TX Team

.vscode/extensions.json, src/logger.teams.ts
- Adds a hex colour highlighting extensions to the list of suggestions
- Removes the comments indicating the colours
[Some developers][1] rightly remarked it was hard to mentally map hex codes to colours. This does it visually.
[1]: https://github.com/guardian/libs/pull/94#issuecomment-756679776
=> style: Add colour highlight extension

.github/workflows/CI.yml
uses https://github.com/guardian/actions-setup-node to manage node in github actions
simpler config, one place to manage node version
=> chore: use actions-setup-node

jest.config.js, src/logger.test.ts
- prevents jest looking for tests in `dist`
- stops the `logger` modules tests actually logging
- doesn't run pointless tests
- keeps the output cleaner
=> test: improve tests a little

src/timeAgo.ts
Removes the `isValidDate` function from `dateAgo`
I originally started to [abstract this funciton into a lib as](https://trello.com/c/EvexVKCw/2734-move-isvaliddate-into-its-own-helper-util-in-libs) it sounded useful but after thinking some more I realised we don't need it anymore. This function was written 9 years ago as part of the [49th PR for Frontend](https://github.com/guardian/frontend/pull/43/files). Back in 2012 a lot was going on. [Vladimir Putin](https://en.wikipedia.org/wiki/Vladimir_Putin) was elected presedent of Russia, the UK notified the WHO that it had discovered a [novel coronavirus](https://en.wikipedia.org/wiki/2012-nCoV) and [Curiosity](https://en.wikipedia.org/wiki/Curiosity_(rover)) touched down on Mars. In addition to these topical events, Typescript was [first …
=> refactor: Remove isValidDate check

README.md, src/cookies.README.md, src/cookies.test.ts, src/cookies.ts, src/getLocale.test.ts, src/getLocale.ts, src/index.ts, src/types/window.d.ts
- Adds cookie module 
- Change locale logic to get the country code from newly [GU_geo_country](https://github.com/guardian/fastly-edge-cache/pull/906) cookie
- Return overridden geolocation if it exist to allow RR team test their banners in different countries
- Call API as fallback when cookie is not present and set its value to cookie
- Frontend PR: https://github.com/guardian/frontend/pull/23739
Faster & more accurate geolocation
=> feat: Get locale from cookie 

package.json, yarn.lock
#181 failed to build because we weren't using `peerDependencies` but a bug in pkgu (https://github.com/guardian/pkgu/commit/62ead251334623e9a7620a28f7e2dceba2b2158e) meant the build didn't break. this should fix both
progress and stability
=> refactor: `@guardian` deps should be peers

jest.config.js
- Allowed `ts-jest` to transform Guardian packages
- Used the `js-with-ts` preset to handle Guardian packages JS files
@sndrs I'm not quite sure what the correct prefix is for this PR. I've used `test:` because it touches the tests, but happy to change if that's not right.
According to [our recommendations](https://github.com/guardian/recommendations/blob/master/npm-packages.md#using-guardian-npm-packages), Guardian packages aren't built to meet the requirements of any environment, and need to be transpiled wherever they are used. Accordingly, `@guardian/types`, added in #181, makes use of ESModules (`import` and `export` statements). These are not supported by default in Node 14, and therefore `@guardian/types` (and any other Guardian packages) needs to be included in our transpilation …
=> test: Allow Jest To Understand Guardian Packages

src/getLocale.ts, src/isBoolean.ts, src/isString.ts, src/isUndefined.ts
Let the Typescript compiler know the type of functions using [type predicates]. Especially useful if you want to filter an array of varying types.
Applied to the following is* methods:
- `isUndefined`
- `isBoolean`
- `isString`
See example [on TS Playground](https://www.typescriptlang.org/play?jsx=0#code/MYewdgzgLgBAhgJwXAnjAvDA2gKBjAcjgIBo9CAjU8g4a-ARjPwCZmYBmdgVzABMApgDMAlmAF8e-YWInsw3ADaL2Ab3hgAXIRAUAVgOBQCMAL7soCbgPZC4iiDfJ2HTgLo4coSLBEQAqtKi4nwYMAAUAPravADWYCAA7mAAlNqRMH4wvILBEhgAfDAZ6KXZQbJ8ANxe4NDwSKgA8kKBuZVhiMgoAHSiilACCOF+bTIhKZ7e9X4AQiAgigJwYGFRMWDxSanpmRAwFAtLK4UwqjgAkAgCUNwIq1AoAA4CIELFGGUEh4vLYAQ1Uw1aawLrNITzX4rfaYMG9fqDYZzI5-Sa1Hx7ADKljEAHM1tFyltkmkPlloAg8adzlcbndVk19IYoD0nggQFAOc8BD1OdjKWBcT1gPZFFEUp9MAQsLoDEYYPy8W4ATggej6nCWorBTCGt0+iIBkMRhBtbjJkA)
[type predicates]: …
=> feat: use type predicates

src/cookies.test.ts, src/cookies.ts
Update `cookies.ts setCookie()` to set cookie expiry dates with [`setUTC`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCDate
) and [`getUTC`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCDate) methods to maintain UTC time.
The current logic for setting cookie expiry dates is setting local timezone time rather than maintaining UTC time.
The test for `setCookie` fails because it (correctly) expects the expiry time to be UTC.
Because non-UTC methods are used to set the expiry date, it incorrectly sets the time to local time.
Hence `expires.toUTCString()` outputs local time rather than the expected adjusted UTC time.
```js
// Date with GMT timezone within BST period
var a = new Date('Mon Jun 14 2021 …
```
=> fix: use setUTC and getUTC methods for setting cookie expiry dates

src/timeAgo.test.ts, src/timeAgo.ts
Achieve 100% coverage in `timeAgo`.
- remove singular verbose “second ago”
- remove singular “day ago”
- add test for future dates
[Greener is better!](https://coveralls.io/builds/40626836/source?filename=src%2FtimeAgo.ts)
=> test: 100% coverage for `timeAgo`

src/cookies.test.ts, src/cookies.ts
Throw an error if the cookie name or value is invalid as suggested by @sndrs 
Make errors explicit.
=> feat: throw error if cookie name or value is invalid

package.json, yarn.lock
* bump rollup from 2.52.7 to 2.53.1
* bump husky from 7.0.0 to 7.0.1
* bump @types/jest from 26.0.23 to 26.0.24
* bump ts-node from 10.0.0 to 10.1.0
=> build(deps-dev): Bump dependencies (12/07)

package.json, yarn.lock
* bump ts-node from 10.1.0 to 10.2.0
* bump tslib from 2.3.0 to 2.3.1
* bump @types/jest from 26.0.24 to 27.0.1
* bump semantic-release from 17.4.4 to 17.4.5
* bump rollup from 2.55.1 to 2.56.2
=> build(deps-dev): Bump dependencies (18/08)

src/format.ts
This change adds the `Correction` option to the `ArticleDesign` enum from `format`.
The change corrects some drift between here and `@guardian/types` following https://github.com/guardian/types/pull/164.
=> feat: Add ArticleDesign.Correction

package.json, yarn.lock
* bump ts-node from 10.2.0 to 10.2.1
* bump rollup from 2.56.2 to 2.56.3
* bump ts-jest from 27.0.4 to 27.0.5
=> build(deps-dev): Bump dependencies (07/09)

src/@types/ophan.README.md, src/@types/ophan.ts
The Ophan thrift model was recently updated ( https://github.com/guardian/ophan/pull/4258 ) to allow for consent related component events. This brings the same change to this repository so that we can correctly send those events from DCR client side.
=> feat: Add Consent related Ophan component types

.github/workflows/CI.yml
This change updates the _ci_ workflow to use caching implemented by [guardian/actions-setup-node](https://github.com/guardian/actions-setup-node) now that it's available. It also swaps out [bahmutov/npm-install](https://github.com/bahmutov/npm-install) for `yarn install --frozen-lockfile` as we no longer need the caching implemented by that action.
=> chore: use built in caching from setup-node action

.github/workflows/PR.yml
- Sets the `validateSingleCommit` option to true in the PR title checker workflow
When using "Squash and merge" on a PR with only one commit, GitHub will suggest using that commit message instead of the PR title for the merge commit, and it's easy to commit this by mistake. Enable this option to also validate the commit message for one commit PRs.
=> chore: Add validateSingleCommit option to pr checker

src/coreWebVitals.README.md, src/coreWebVitals.ts
Matches JSDoc to documentation
@oliverlloyd has mentioned this is the proper way
=> fix: update JSDoc to match documentation

.gitignore, src/@types/ophan.ts
Adding a new component LIVE-BLOG-PINNED-POST to track the new live blog feature where a post can be pinned at the top of a liveblog.
This has already been created and deployed in Ophan: https://github.com/guardian/ophan/pull/4337
More details about what kind of questions we'll be answering using this component on this card: https://trello.com/c/ZOVxR6F5/179-tracking-for-pinned-posts
=> feat: add pinned post component

src/index.test.ts
makes sure exports haven’t accidentally changed 
doesn't check for new types being added though, because i can’t work out how to test for that...
=> test: Add package verification test

src/@types/ophan/index.ts
This PR adds a new component STICKY_VIDEO and also adds two actions STICK & CLOSE to ophan types.
In order to emit tracking event to ophan when a sticky video sticks to screen and when the sticky video is closed.
Another PR is created in ophan to add these to the thrift https://github.com/guardian/ophan/pull/4440
=> feat: add sticky_video to ophan component type

src/@types/ophan/index.ts
This PR adds a new action RETURN to ophan types. 
In order to emit tracking event to ophan when a sticky video is returned to its original location.
Another PR is created in ophan to add this action to the thrift https://github.com/guardian/ophan/pull/4440
=> feat: add RETURN to ophan actions

package.json, yarn.lock
Upgrades Typescript to v4.2
For the loadScript function, TypeScript was taking the following type signature:
```ts
const loadScript = (
src: string,
props?: Omit<Partial<HTMLScriptElement>, 'src' | 'onload' | 'onerror'>,
): Promise<Event | undefined>
```
And outputting:
```ts
const loadScript: (src: string, props?: Pick<Partial<HTMLScriptElement>, "normalize" | "hidden" | "dir" | "slot" | "style" | "title" | "text" | "blur" | "click" | "focus" | "scroll" | "async" | "attributes" | "defer" | "type" | "charset" | "crossOrigin" | "event" | "htmlFor" | "integrity" | "noModule" | "referrerPolicy" | "addEventListener" | "removeEventListener" | "accessKey" | "accessKeyLabel" | "autocapitalize" | "draggable" | "innerText" | "lang" | "offsetHeight" | "offsetLeft" | "offsetParent" | "offsetTop" | …
```
=> fix: upgrade typescript to 4.2

src/coreWebVitals/index.test.ts, src/coreWebVitals/index.ts
Prevents loading the `web-vitals` module when the user is not in the sampling group and the sampling has not been bypassed.
Less JS sent to the vast majority (~99%) of our users.
=> feat!: Load `web-vitals` asynchronously

src/datetime/timeAgo.test.ts, src/datetime/timeAgo.ts
Fixes the time separator for the `withTime` method.
From [the Guardian and Observer style guide: T][T]
> **times**
> 1am, 6.30pm, etc; 10 o’clock last night but 10pm yesterday; half past two, a quarter to three, 10 to 11, etc; 2hr 5min 6sec, etc; for 24-hour clock, 00.47, 23.59; noon, midnight (not 12 noon, 12 midnight or 12am, 12pm).
[T]: https://www.theguardian.com/guardian-observer-style-guide-t
=> fix: time separator is `.`

.github/workflows/yarn-lock.yml, package.json, yarn.lock
- merges some dependabot PRs
- runs `yarn upgrade`
- adds `yarn-lock-changes` to more easily identify changes in `yarn.lock`
=> chore: Bump deps

src/ophan/@types/index.ts
This PR adds a `KEY_EVENT_CARD` Ophan component type.
We're in the process of creating a new key events timeline carousel, the first step of which has been to create new key event cards: https://github.com/guardian/dotcom-rendering/pull/4696
In order to track clicks on these new cards, we need a new componentType.
The corresponding PR in Ophan is here: https://github.com/guardian/ophan/pull/4617
=> feat(ophan): Add `key_event_card` ophan component type

src/ophan/@types/index.ts
The identity team use the `SIGN_IN` and `CREATE_ACCOUNT` action, which we noticed was missing from the `OphanAction` type, and the `IDENTITY_AUTHENTICATION` `OphanCompnent` type.
From the definitions in https://dashboard.ophan.co.uk/docs/thrift/componentevent.html
This PR adds those actions in so that they're available for use.
=> feat(ophan): add additional types to Ophan

src/logger/teamStyles.ts, static/logger.svg
Add the Identity team to the logger
So the Identity team can use these logs to identify their own logs in other platforms, e.g. frontend/dcr, as well as our own.
=> feat(logger): add `identity` team to logger

.github/CODEOWNERS
The CODEOWNERS file was showing errors, fixed some of them in the following ways.
- `gtrufitt` no longer has access, removed from the file.
- `guardian-frontend-team` doesn't seem to exist any more, removed from the file. Added `dotcom-platform` instead.
Added `apps-rendering` and `dotcom-platform` as owners of the `format` module.
GitHub was showing three errors in the CODEOWNERS file. I've fixed two of them as described above. There's still a problem with `commercial-dev`, and I can see a similar error has appeared for the new teams I've added. Perhaps we need to update the repo permissions for this to work?
I've made the `format` ownership change because I think the Apps-Rendering and Dotcom teams probably own this module and any downstream repos that will be affected by changes to it …
=> chore(codeowners): remove old, add new CODEOWNERS

src/index.ts
`log` takes a arg of type `TeamName`
=> fix: export `TeamName` for `log`

package.json, src/cookies/getCookie.ts, src/cookies/setCookie.ts, src/cookies/setSessionCookie.ts, src/datetime/timeAgo.ts, src/loadScript/loadScript.test.ts, src/loadScript/loadScript.ts, tsconfig.json, yarn.lock
Adds `@guardian/tsconfig` to the typscript config
It's stricter (in a good way) and preps the code for import to https://github.com/guardian/csnx
=> fix: Use `@guardian/tsconfig`

scripts/generateSvg.logger.teams.ts, src/logger/@types/logger.ts, src/logger/log.ts, src/logger/logger.test.ts, src/logger/teamStyles.ts
Remove type assertions from logger by creating a `getTeamSubscriptions` abstraction.
Checks unkown value at runtime for better type safety.
=> fix: remove type assertions from logger
